DIM B$(65)
'
SCREEN 13
'
B$(0) = "TTTTTTTTTTTTVTTTTTTTVTVTVTVVVTTTTTTTTTVTVVVTVVVVVVVVVVVVVVYYYYYY"
B$(1) = "TZTZTTTTTTTTTTTTTTTTTTTTVTVTTTTTTTVTVTVTVTVTVYVVYVVVVYVVYVYYYYYY"
B$(2) = "TZTTTTTTTTTTTTTTTTVTVTVVVTVTTTVVYVYYYVYVVTVTVVVVVVVVVVYVVVYYYYYY"
B$(3) = "TTTTTTTTTTTTTTTTTTTTTTVTTTVVYY[XQXQQQQQUWYYVVTVVVVVVVVVVVYYYYYYY"
B$(4) = "TTTZTTTTTTTTTTTTTTTTTTTTVYWSQQQQQQQQQQQQQQURYVVVVYVVVYVVVVYYYVYY"
B$(5) = "TZTZTZTTTZTTTTTTTTTTTTVYWXQQQQQQQQQQQQQQQQQQURYVVVVVVVVVVVYYYYYV"
B$(6) = "TZTZTZTTTTTTTTTTTTTTTVSQQQQQQQQQQQQQQQQQQQQQQQWVVVVYVVVYVVYVYVYV"
B$(7) = "TZTZTZTTTZTTTTTZTTTVWUQQQQQQQQQQQQQQQQQQQQQQQQQRYVVVVVVVVVVVVVYY"
B$(8) = "TZTZTZTTTZTZTZTTTTYUQQQQQQQQQQQQQQQQQQQQQQQQQQQQWVVVVVVVVYYVYVYV"
B$(9) = "TZTZTZTZTZTZTTTTTYUQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQRVVVYVVVVVVYVYV"
B$(10) = "TZTZTZTZTZTTTTTTRUQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQXRVVVVVVVVVYVYV"
B$(11) = "TZZZTZTZZZTZTTTVUQQQQQQQQQQUUUS[[WW[UXQQQQQQQQQQQQXRVVVVVVVVYVYV"
B$(12) = "TZTZTZTZTZTZTTV[QQQQQQQQQU[WWRRYYVYYRR[SXXQQQQQQQQQ[VVVYVVYVYVVV"
B$(13) = "TZTZZZTZTZTTTTRQQQQQQQQQUWWRYVVTVTVVVVYRWWSXQQQQQQQXRVYVVTVVYVYV"
B$(14) = "TZTZTZTZTZTTTT[QQQQQQQQUWRRVVVVTTTTTTTVVYYW[UXQQQQQQSVVVVVVVVVVV"
B$(15) = "ZZTZZZZZTZTZTVXQQQQQQQXWRYYVVTTTTZTTTZTTVVRR[[UQQQQQQRVVVYVVVVVV"
B$(16) = "ZZTZTZTZTZTTVRQQQQQQQQ[RYYYVVTTZTZTZTZTZTTYYRW[UQQQQQSVVVVVVYVYV"
B$(17) = "ZZTZZZTZTZTTY[QQQQQQQUWYYVVTVTTZTZTZTZTZTTVVYRW[XQQQQUYVVVVVVVVV"
B$(18) = "ZZZZZZTZTZTTY[QQQQQQQSRYYVVTTTTZZZZZTZZZTTVVYYRWSQQQQXRVVVVVVVVV"
B$(19) = "ZZZZTZTZTZTTRUQQQQQQQSRYVVVTTTTZTZZZTZTZTTTTYYRWSXQQQXYVVVVVVVYV"
B$(20) = "ZZZZTZZZTZTVRUQQQQQQQ[RYVTVTTTTZZZTZTZZZTTTTVYYW[UQQQUYTVTVYVVVV"
B$(21) = "ZZTZZZTZTZTVWUQQQQQQQ[RYVTTTTZTZZZZZTZTZTTTVVYRW[SQQQXRTVTVVVVVV"
B$(22) = "ZZZZZZZZTTVYWUQQQQQQQ[RYVTTTZZZZZZZZTZTZTTTTVYRW[SQQQUYTVTVVVVVV"
B$(23) = "ZZZZTZTZTZVYWSQQQQQQXWRYVVVTZZZZZZTZTZTZTZTTVVRR[SQQQSVTTTVVVYVV"
B$(24) = "ZZZZTZZZTZTYR[QQQQQQURRYRWRTZZVVYVYTTTTZTTVTVYYRW[QQQRTTTTTTVVVV"
B$(25) = "ZZZZZZTZZTTYRWUUXQQQSRYVWWRYYYRWWYYYYVVTVTVVVYRR[SQQQYTTTTVTVVVV"
B$(26) = "ZZZZTZZZZZTYRR[[SQQQ[RYYWRRYYVVR[RYVVTTVYVVYRRWW[SQQSVTTTTTTVVVT"
B$(27) = "ZZTZZZZZTZVYRRRRSQQURYYYRRW[[RWWRRYVVZTTTZTRSUUUUXXQWTTTTTTTVVVV"
B$(28) = "ZZTZZZTZTZTVYRRYWXQSYVYYYR[UXXX[[RYVYVVTTTYWSUQQXXU[RZTTTTTTVTVT"
B$(29) = "ZZZZZZZZZZZVYYYVYSQWYVVVVTYYRRWW[RYYRVVYYVVYWWSUQURRRTTTTTTTVVVT"
B$(30) = "ZZZZZZTZZZTTYYYTV[SRYVVVTTVVYYYVVVYRYTVRWWSXXUSUXSYYRTTTTTTTVTTT"
B$(31) = "ZZTZZZZZZZTTVYYTTYRYVVVTTZTTVTTTTTVVTZVR[RWSUXXUS[WRRTTTTTTTVTTT"
B$(32) = "ZZZZZZTZZZZTVYVTTVYYVTTTTZTTTTTZTTVTZZVYRYYYRWS[WYRRWRTZTZTTTTTT"
B$(33) = "ZZZZZZZZZZZTVYYTTTYYVTTTTTTZZZTTVTTTTTVYRYYYRRWWWVVYYTTZTZTZTTTT"
B$(34) = "ZZZZZZZZZZTTYYYVTTYYYTTTTZZZTTVVVTTZZTVYRYYVYYRRRVVYVZTTTTTTTTTT"
B$(35) = "ZZZZZZTZZZZTYYYVTTYYYVTTTZZTVVYVTTTZTZVYRYYVVVYYYVVVTZTZTTTTTTTT"
B$(36) = "ZZZZZZZZZZZTVYYVVVYYVVVTTTTTYVVVVTTTTZTVRYYYVTVVYVTZTZTZZZTTTTTT"
B$(37) = "ZZZZZZZZZZZTVYYYWWRVVYVVVVVYYTTVYYYVTTVYRYYVVVRYRYTZTZTZTZTZTTTT"
B$(38) = "ZZZZZZZZZZTZVYYY[SWVVVVVVVVVVTTVVVYYYYRRWYYVVTVYRYTZTZZZZZTTTTTT"
B$(39) = "ZZZZZZZZZZZZVVYYW[RVVTTVVTVTVTTTTTVVYYRRRYVVVVVYRVTZZZTTTZTTTTTT"
B$(40) = "ZZZZZZZZZZZZTVYYRRRVVTVTTTTTYYVVVVVTVVVYYVYVVVVYYTZZTZTZTZTTTTTT"
B$(41) = "ZZZZZZZZZZZZTTYYRYRYVTTTTZTYWRVTVTTVYVYYYYYVVVYRYZTZTZZZZZTTTTTT"
B$(42) = "ZZZZZZZZZZZZTZVYRYYYVTTTTZTTVVVTTZZZVTVR[RYVVVRRVZZZZZZZZZTZTTTT"
B$(43) = "ZZZZZZZZZZZZZZVYRYRRYTTTTZTZTVVTVTVTVVYR[RVVVVRYTZTZTZZZZZZZTTTT"
B$(44) = "ZZZZZZZZZZZZZZVVYYYYRVVTTZTZTTTTTTTTVVRRRVVTTYRYTZTZTZZZZZTZTTTZ"
B$(45) = "ZZZZZZZZZZZZZZVVYYYYRYVVTTTZZZTTTTVVVVYYYVVTVYRVZZTZZZZZZZZZTTTT"
B$(46) = "ZZZZZZZZZZZZZZVYYVYYWRYVVTTTTZTZTTTTVTVVVVVVYYYZZZZZZZTZZZZZTTTZ"
B$(47) = "ZZZZZZZZZZZZZTVYYVVYWWRYVTTZZZZZZZTZTTTTVVVYRYTZTZZZZZZZZZZZTZTZ"
B$(48) = "ZZZZZZZZZZZZZTVYYVVVRWWYYVTTTZZZZZZZTTTTVYYYRVZZTZZZZZZZZZZZTTTZ"
B$(49) = "ZZZZZZZZZZZZZTYYYTVTYR[WRYVTTTZZZZZZTTVVYYRRRZZZZZZZZZZZZZZZTTTZ"
B$(50) = "ZZZZZZZZZZZZZTYYVTTTVYWWWRRYVTTZZZTZTTVVRRWRVZZZZZZZZZZZZZZZZZTZ"
B$(51) = "ZZZZZZZZZZZZZTYYVVTTTTYR[WWWRVVTTTTTTTVYWWRVTZZZZZZZZZZZZZZZTZTT"
B$(52) = "ZZZZZZZZZZZZTVYYVTVTTZVVW[S[[RYYVVVVVYRW[RYTZZZZZZZZZZZZZZZZTTTZ"
B$(53) = "ZZZZZZZZZZZZVVYVVTVTTTTTVR[SSSSWWRWRW[S[RVVZZZZZZZZZZZZZZZZZTTTT"
B$(54) = "ZZZZZZZZZZTTVVVTVTTTTTTTTVYR[SUUUUUUXXSRYVTZZZZZZZZZZZZZZZZZTZTZ"
B$(55) = "ZZZZZZZVW[[WYYVVVTTTTTTTTTVVRRW[SSUSUSWYVTZZZZZZZZZZZZZZZZZZTZTZ"
B$(56) = "ZZZZTZYXQQQQQUWVVTTZTZTZTTTTVVYYRRWW[WRVTZZZZZZZZZZZZZZZZZZZTTTZ"
B$(57) = "ZZZTYSQQQQQQQQQUWVVTTZTTTTTTTTVYYRWW[WYZZZZZZZZZZZZZZZZZZZZZTZTZ"
B$(58) = "ZZT[QQQQQQQQQQQQQQ[YVTTTTZTTTTVVYYRR[WYZZZZZZZZZZZZZZZZZZZZZTZTZ"
B$(59) = "VWQQQQQQQQQQQQQQQQQQSYVTTTTTVTVVYYRW[[[VZZZZZZZZZZZZZZZZZZZZTTTT"
B$(60) = "QQQQQQQQQQQQQQQQQQQQQQQSRYVVVVVVYYRW[[U[VZZZZZZZZZZZZZZZZZZZTZTZ"
B$(61) = "QQQQQQQQQQQQQQQQQQQQQQQQQQUWRYYYYYRR[SQQXYTZZZZZZZZZZZZZZZZZTZTZ"
B$(62) = "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQSWWRWW[SQQQQRTZZZZZZZZZZZZZZZZTTTZ"
B$(63) = "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQWTTTZTZZZZZZZZZZZTTTT"
'
' Palette DATA Next
'
B$(64) = "AAAABB\\\LLLoppHHHijjVVVDDDbbbvvvQRRAAAAAAAAAAAA"
'
LINE (0, 0)-(63, 63), 7, BF
LINE (0, 0)-(63, 63), 15, B
LINE (63, 1)-(63, 63), 8
LINE -(0, 63), 8
'
' Tricky code to read old palette data
'
OUT &H3C7, 16 ' Set to start at slot 15
'
FOR a% = 0 TO 15
  r% = INP(&H3C9)
  g% = INP(&H3C9)
  B% = INP(&H3C9)
  B$(65) = B$(65) + CHR$(r% + 65) + CHR$(65 + g%) + CHR$(65 + B%)
NEXT a%
'
' Tricky code to read new palette data
'
OUT &H3C8, 16 ' Set to start at slot 15
'
FOR a% = 0 TO 15
  r% = ASC(MID$(B$(64), a% * 3 + 1, 1)) - 65
  g% = ASC(MID$(B$(64), a% * 3 + 2, 1)) - 65
  B% = ASC(MID$(B$(64), a% * 3 + 3, 1)) - 65
  OUT &H3C9, r%
  OUT &H3C9, g%
  OUT &H3C9, B%
NEXT a%
'
' Tricky code to read picture data
'
FOR yy% = 1 TO 62
  FOR xx% = 1 TO 62
    col% = ASC(MID$(B$(yy%), xx% + 1, 1)) - 64
    PSET (xx%, yy%), col%
  NEXT xx%
NEXT yy%

