DECLARE SUB LoadPalette ()
'
SCREEN 13
'
CALL LoadPalette

SUB LoadPalette
  '
  slot% = 0
  '
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  palette$ = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": GOSUB SetPalette
  '
  EXIT SUB
  '
SetPalette:
  '
  FOR t% = 1 TO 48 STEP 3
    OUT &H3C8, slot% ' Write RGB values to slot
    '
    red% = ASC(MID$(palette$, t% + 0, 1)) - 32: OUT &H3C9, red%
    grn% = ASC(MID$(palette$, t% + 1, 1)) - 32: OUT &H3C9, grn%
    blu% = ASC(MID$(palette$, t% + 2, 1)) - 32: OUT &H3C9, blu%
    '
    slot% = slot% + 1
  NEXT t%
  '
  RETURN
  '
END SUB

